@token=ghp_I7MEMkxvqdb6BzmGOXniBE9aGAqlcl0....
@sha=f887c8408978e25f84986bd490f4191c376246f8
@tag=4.0.1
@tagger=ernst-stoeger
@taggermail=ernst.stoeger@integrations.at
@repo=www.bico.at


### Create tag
POST https://api.github.com/repos/arambazamba/{{repo}}/git/tags HTTP/1.1
content-type: application/json
accept: application/vnd.github.v3+json
Authorization: token {{token}}

{"tag":"{{tag}}","message":"version-4","object":"{{sha}}","type":"commit","tagger":{"name":"{{tagger}}","email":"{{{{taggermail}}}}","date":"2022-06-21T06:53:35-07:00"}}

### Createt tag ref
POST https://api.github.com/repos/arambazamba/{{repo}}/git/refs HTTP/1.1
content-type: application/json
accept: application/vnd.github.v3+json
Authorization: token {{token}}

{
  "ref": "refs/tags/{{tag}}",
  "url": "https://api.github.com/repos/arambazamba/{{repo}}/git/refs/tags/{{tag}}",
  "sha": "{{sha}}",
  "object": {
    "sha": "{{sha}}",
    "type": "tag",
    "url": "https://api.github.com/repos/arambazamba/{{repo}}/git/tags/{{sha}}"
  }
}