##### Stage 1 - Create the build-image -> SDK, more vulnerabel, bigger
FROM node:14 as node
LABEL author="Alexander Pajer"
WORKDIR /app
COPY package.json package.json
RUN npm install
COPY . .
RUN npm run build

##### Stage 2 - Create the run-time-image  -> no SDK, less vulnerabel (less tool), smaller
FROM nginx:alpine
VOLUME /var/cache/nginx

# Copy the build output
COPY --from=node /app/dist/food-shop-ui /usr/share/nginx/html 
# NGINX config with URLRewrite for SPAs
COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf

# docker build --rm -f "dockerfile" -t food-shop-ui .
# docker run -d --rm -p 5052:80 food-shop-ui
# http://localhost:5052/

# Publish Image to dockerhub
# docker tag food-shop-ui arambazamba/food-shop-ui
# docker push arambazamba/food-shop-ui